apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: electronic-signature-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: electronic-signature-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /set-electronic-signature
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /set-electronic-signature
